# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /workspaces/cs79-nshiv3-shrijan2-yueranw2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /workspaces/cs79-nshiv3-shrijan2-yueranw2

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /workspaces/cs79-nshiv3-shrijan2-yueranw2/CMakeFiles /workspaces/cs79-nshiv3-shrijan2-yueranw2/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /workspaces/cs79-nshiv3-shrijan2-yueranw2/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /workspaces/cs79-nshiv3-shrijan2-yueranw2/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named tests

# Build rule for target.
tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tests
.PHONY : tests

# fast build rule for target.
tests/fast:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/build
.PHONY : tests/fast

#=============================================================================
# Target rules for targets named src

# Build rule for target.
src: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 src
.PHONY : src

# fast build rule for target.
src/fast:
	$(MAKE) -f src/CMakeFiles/src.dir/build.make src/CMakeFiles/src.dir/build
.PHONY : src/fast

tests/catch/catchmain.o: tests/catch/catchmain.cpp.o

.PHONY : tests/catch/catchmain.o

# target to build an object file
tests/catch/catchmain.cpp.o:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/catch/catchmain.cpp.o
.PHONY : tests/catch/catchmain.cpp.o

tests/catch/catchmain.i: tests/catch/catchmain.cpp.i

.PHONY : tests/catch/catchmain.i

# target to preprocess a source file
tests/catch/catchmain.cpp.i:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/catch/catchmain.cpp.i
.PHONY : tests/catch/catchmain.cpp.i

tests/catch/catchmain.s: tests/catch/catchmain.cpp.s

.PHONY : tests/catch/catchmain.s

# target to generate assembly for a file
tests/catch/catchmain.cpp.s:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/catch/catchmain.cpp.s
.PHONY : tests/catch/catchmain.cpp.s

tests/graphtests.o: tests/graphtests.cpp.o

.PHONY : tests/graphtests.o

# target to build an object file
tests/graphtests.cpp.o:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/graphtests.cpp.o
.PHONY : tests/graphtests.cpp.o

tests/graphtests.i: tests/graphtests.cpp.i

.PHONY : tests/graphtests.i

# target to preprocess a source file
tests/graphtests.cpp.i:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/graphtests.cpp.i
.PHONY : tests/graphtests.cpp.i

tests/graphtests.s: tests/graphtests.cpp.s

.PHONY : tests/graphtests.s

# target to generate assembly for a file
tests/graphtests.cpp.s:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/graphtests.cpp.s
.PHONY : tests/graphtests.cpp.s

tests/splittests.o: tests/splittests.cpp.o

.PHONY : tests/splittests.o

# target to build an object file
tests/splittests.cpp.o:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/splittests.cpp.o
.PHONY : tests/splittests.cpp.o

tests/splittests.i: tests/splittests.cpp.i

.PHONY : tests/splittests.i

# target to preprocess a source file
tests/splittests.cpp.i:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/splittests.cpp.i
.PHONY : tests/splittests.cpp.i

tests/splittests.s: tests/splittests.cpp.s

.PHONY : tests/splittests.s

# target to generate assembly for a file
tests/splittests.cpp.s:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/splittests.cpp.s
.PHONY : tests/splittests.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... tests"
	@echo "... src"
	@echo "... tests/catch/catchmain.o"
	@echo "... tests/catch/catchmain.i"
	@echo "... tests/catch/catchmain.s"
	@echo "... tests/graphtests.o"
	@echo "... tests/graphtests.i"
	@echo "... tests/graphtests.s"
	@echo "... tests/splittests.o"
	@echo "... tests/splittests.i"
	@echo "... tests/splittests.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /workspaces/cs79-nshiv3-shrijan2-yueranw2/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

